# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female')], default='', max_length=2)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_images', models.ImageField(blank=True, default='profile-images/profile-image-default.png', upload_to='profile-images')),
                ('university', models.CharField(blank=True, default='', max_length=100)),
                ('major', models.CharField(blank=True, default='', max_length=100)),
                ('is_publisher', models.BooleanField(default=False)),
                ('last_applied', models.DateTimeField(default='1970-01-01T00:00+00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('TOWNHOUSE', 'Townhouse')], max_length=10)),
                ('min_bedroom_num', models.IntegerField(default=0)),
                ('max_bedroom_num', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('contact_person', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(blank=True, default='property-images/property-image-default.png', upload_to='property-images')),
                ('upload_time', models.DateTimeField(default='1970-01-01T00:00+00:00')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentnest.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentnest.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('votes', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=500)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentnest.Property')),
            ],
        ),
    ]
